services:
  - type: web
    name: teamflow
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/dev.db
      - key: NEXTAUTH_SECRET
        value: teamflow-super-secret-key-2026
      - key: AUTH_SECRET
        value: teamflow-super-secret-key-2026
      - key: NEXTAUTH_URL
        value: https://teamflow.onrender.com
      - key: AUTH_TRUST_HOST
        value: "true"
    disk:
      name: teamflow-data
      mountPath: /app/prisma
      sizeGB: 1
